### ISSUE TITLE
Build logs are hard to read, link non-obvious

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1080]
## Summary

Build logs on b.s.i appear in a little text area. It's not obvious to developers that the first line of the log is actually the url to the entire log file on launchpad. Could we perhaps get a nice link or button which allows the developer to "Show whole log"?

## Process

Start a build, visit b.s.i to look at the log of a failed one.

## Current and expected result

Developers will typically scroll through the log or copy/paste it out to a text editor, not realising the first line is a url.

## Screenshot

![screenshot from 2018-04-06 16-36-44](https://user-images.githubusercontent.com/1841272/38430548-752e4666-39b9-11e8-8882-b02356bb074f.png)

**Comment by cjwatson** [comment]
FWIW, the URL there is just intended to make it easier to get from the *build log* to the *build* on Launchpad.  If you want to present that URL, please don't parse it out of the log file - there are much more appropriate ways to get hold of it via the API.

**Comment by evandandrea** [comment]
Yeah, I see this as equivalent to the “Raw log” button on Travis:
![8708a043-243d-4aeb-b5e8-f8604926d63b](https://user-images.githubusercontent.com/1523179/39869818-dcc894a4-5456-11e8-83c0-844e18756029.jpeg)

 We shouldn’t link to the Launchpad UI. Launchpad is an implementation detail.

**Comment by evandandrea** [comment]
Yes

**Comment by matthewpaulthomas** [comment]
Proposed design:

![build page](https://user-images.githubusercontent.com/19801137/40310733-a9bfea8c-5d05-11e8-8c4d-90eba5b5158a.png)

> Build logs on b.s.i appear in a little text area.

I’ve shown the log as being part of the page content, no longer in a text area at all. Since the log can be extremely long, this requires that nothing important go below it. Therefore, “To test this build” and “Ready to release?” go above the build log, not below. (Adopting Vanilla’s [code snippet](https://docs.vanillaframework.io/en/patterns/code-snippet) for the commands would make these boxes take up less space.)

I’m aware that inserting the log into the page like this is non-trivial to implement. If it’s _extremely_ difficult to implement, next best would be to size the textarea dynamically so that it is always nearly as tall as the viewport.

> Could we perhaps get a nice link or button which allows the developer to "Show whole log"?

Added “Raw log” button.

**Comment by matthewpaulthomas** [comment]
[Design approved](https://github.com/CanonicalLtd/snapcraft-design/pull/467), and [spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749).

**Comment by solazio** [comment]
@lilyvidenova perhaps you can have a look at the approved designed for this and let me know if you are happy with it.

**Comment by lilyvidenova** [comment]
Hm @solazio - are there supposed to be designs in the "design approved" link?

**Comment by solazio** [comment]
@lilyvidenova that's what I thought but it seems I was wrong. Maybe @matthewpaulthomas has more knowledge of this?

**Comment by solazio** [comment]
This is fixed in the `Builds` tab in snapcraft.io
