### ISSUE TITLE
Loading repos may take a long time

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#1110]
This is a follow up to improvements around loading repos list (#1006, #1088).

If repository list is long (more then 70 repos as in snapcrafters organisation) and repos are not memcached (memcache expires in an hour) it may take significant time (more then 10 seconds) to load full list of user repos.

It would be good to find a way to improve this load time.

Currently it seems that loading such a long list from LP (all repos for user and their orgs) and calls to ensure these repos have webhook in LP are taking most of the time.

**Comment by matthewpaulthomas** [comment]
This _probably_ involves a bit of UI design for showing progress, depending on which approach(es) we take:
- Quicker: If the code can actually be sped up to take less than ~2 seconds, the UI might not need changing at all.
- Fewer: If we get the list in batches, so that the first repos appear sooner, we’ll need something to indicate that the list isn’t complete yet. (Perhaps retiring the spinner, in favour of a few [animated skeleton items](https://codepen.io/oslego/pen/XdvWmd) below any repos loaded so far.)
- Less: If we show less about each repo initially, we’ll need something to indicate that the empty columns will be filled soon. (Perhaps animated skeleton cells.)
- Counted: Independently of all of those, if getting the count of repos is much faster than getting the full list, we could use that to calculate and show determinate progress (perhaps with a progress bar, or with empty table rows).

**Comment by bartaz** [comment]
> Quicker: If the code can actually be sped up to take less than ~2 seconds, the UI might not need changing at all.

This highly depends on number of repos users have, network speed and other factors independent from 'the code'. While it probably loads in less then 2 seconds for most users (those who have just a couple of repos), there always will be some (like snapcrafters team) with exceptionally long list to load.

> Fewer: If we get the list in batches, so that the first repos appear sooner, we’ll need something to indicate that the list isn’t complete yet. (Perhaps retiring the spinner, in favour of a few animated skeleton items below any repos loaded so far.)

It it one of the approaches that is most feasible from implementation point of view with current state of LP APIs. It won't be trivial 'paging', as we may have different sources of data for different GH users and organisations (some may come from API, some from cache).
Some approach (that would require bit of investigation) would be to return immediately only data that is already in cache (not to wait for API calls) and load rest of 'batches' progressively. 

> Less: If we show less about each repo initially, we’ll need something to indicate that the empty columns will be filled soon. (Perhaps animated skeleton cells.)

We already show the list before we know build status, the only other thing that we could postpone is 'configured' status. While it would possibly cut down a bit of load time, debugging shows it may not be a significant gain.

> Counted: Independently of all of those, if getting the count of repos is much faster than getting the full list, we could use that to calculate and show determinate progress (perhaps with a progress bar, or with empty table rows).

Currently not possible (with existing LP APIs), not sure if from LP perspective giving us the number would be significantly quicker then giving the list.

**Comment by solazio** [comment]
This is now fixed on snapcrat.io
