### ISSUE TITLE
When you add a new repo (with some already added) the top one still opens

### ISSUE THREAD

**Issue by jamiedawsonyoung** [canonical-web-and-design/build.snapcraft.io#509]
**What happens:** 
When you add a repo after having added some previously the top repo open. 

**What I expected:**
- The repo row I just added should open
- The top repo row from a list of "just added" repos opens
- No row opens (as I've already added some)

**Comment by bartaz** [comment]
This is likely the result of implementing automatic expanding of rows as defined in first time flow: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q0b3jpi4vtot

First repo without name registered will be expanded.
If you add new repo the first one still doesn't have a name, so is expanded.

If it doesn't seem right I guess we would need some exceptions or corner cases defined - when rows should be expanded and when not.

**Comment by matthewpaulthomas** [comment]
If you click “Add repos…” after having already added a repo, the first-time meter and text should go away, because you’ve exited the first-time path of add → name → configure. At that point we assume that you know what you’re doing and don’t need the meter+text any more.

Therefore, it would be odd for the meter+text to reappear once you close the dialog.

The row expansion exists only to help you follow the step in the first-time text: “Great! Next, register a snap name for publishing.” So if the text isn’t there, the expansion shouldn’t be there either.

[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q0b3jpi4vtot): “As an exception to these conditions, the first-time flow should not appear if: …you have at least one repo added, and you have ever chosen ‘Add repos…’.”

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
