### ISSUE TITLE
notifications reflow page

### ISSUE THREAD

**Issue by earnubs** [canonical-web-and-design/build.snapcraft.io#558]
Notifications like the beta notification "Hey, got a spare five minutes…" are in flow and when inserted into the DOM cause a reflow of everything beneath, which is most of the app, and impinge on UI performance severely.

To fix, create space for notification to appear in a fixed (absolute) position.

Read more: http://www.stubbornella.org/content/2009/03/27/reflows-repaints-css-performance-making-your-javascript-slow/

**Comment by bartaz** [comment]
Apart from performance hit on browser it simply also makes all the content below notification move when user is interacting with the page.

Because Beta Notification appears after 2 minutes delay users will be likely doing something on a page when it happens, which may be unexpected (when for example page moves in the middle of the click).

**Comment by matthewpaulthomas** [comment]
We deliberately chose that it would be in flow, because if it wasn’t, it would smother the hierarchy navigation (a.k.a. breadcrumbs) on a repo page or build page.

An alternative might be to put it in a fixed position near the bottom of the viewport.

**Comment by jamiedawsonyoung** [comment]
Lets leave it as it is for now…

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
