### ISSUE TITLE
"To test this build…" text no longer shown [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#640]
<img width="1268" alt="screen shot 2017-04-19 at 09 39 23" src="https://cloud.githubusercontent.com/assets/1523179/25170966/34822172-24e4-11e7-8d03-173d044ac109.png">

The ["To test this build…" text](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749) is no longer shown on the build page.

**Comment by bartaz** [comment]
@ev Is this a new issue that's happening to you now on prod? I can see the install instructions just fine for this build:

![screen shot 2017-04-19 at 10 53 25](https://cloud.githubusercontent.com/assets/83575/25171560/8daca0ec-24ee-11e7-8ac2-57a9f815c803.png)

If it is happening still to you can you post a screenshot of Network panel of browser dev tools, to see if there are any API calls failing?

Thanks.

**Comment by bartaz** [comment]
@ev Or... I may have an idea what happened.

Now that we can ask LP for revision number for given build we are showing these instructions once we get revision from LP.
But it doesn't happen until snap is published in the store.

So, the build status may show 'Successfully built' already (because it was built in LP), but until it's published (which we don't show yet anywhere in UI) install instructions will not be visible.

So once build is 'Successfully built' there maybe some time (couple of minutes) until it's published and install instructions are shown.
This should be fixed once we properly show publication status for builds. I'm not sure if we have a separate task for that now...

**Comment by evandandrea** [comment]
Yes, this was on production moments before filing the issue. Returning to the page once it's published shows the correct message.

As you suggest, saying "Built, publishing soon" (#406) would alleviate this some.

**Comment by nottrobin** [comment]
build.snapcraft.io i sbeing retired, and is replaced by a new experience. I don't think this is relevant any longer.
