### ISSUE TITLE
"Postpone refreshes" in by-revision install instructions [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#641]
<img width="594" alt="screen shot 2017-04-19 at 11 53 44" src="https://cloud.githubusercontent.com/assets/1523179/25176665/de20109c-24f6-11e7-90a7-bcd35065f4bd.png">

The instructions for by-revision installation of a snap suggest that it will not be automatically updated, but this is not accurate. I've [discussed it](https://forum.snapcraft.io/t/desired-refresh-behaviour-for-by-revision-installation/226/10) with Gustavo and Bret, and we should instead suggest they tell snapd to postpone refreshes by several hours.

This snapd feature is not implemented yet, so I'm marking this issue as blocked.

**Comment by magdalena-mirowicz** [comment]
@evandandrea can you confirm why this one is blocked?

**Comment by evandandrea** [comment]
Sure, it's blocked because we don't yet have a way to postpone refreshes for N hours.

**Comment by matthewpaulthomas** [comment]
If I’m understanding that forum thread correctly, it’s a little more complicated than that: our current UI text does not match either current reality _or_ what the snapd developers are proposing. Fixing that doesn’t require waiting for the snapd developers to implement any new feature; we could adapt the UI to current reality instead.
<table>
<tr><th>What build.snapcraft.io claims/implies</th><th>What currently happens</th><th>What snapd developers are proposing</th></tr>
<tr><td rowspan="2">Anyone can install any specific revision ever published</td><td>? <strong>(A)</strong></td><td>Publisher/collaborators can install any of the last three revisions <strong>(B)</strong>, except that they can install a revision before their currently-installed one <em>only if they had previously installed it</em> <strong>(C)</strong></td></tr>
<tr><td>? <strong>(D)</strong></td><td>Non-publishers/collaborators can’t install past revisions at all <strong>(E)</strong></td></tr>
<tr><td>If you install a specific revision, it will not be updated automatically</td><td>If you install a specific revision, it will be updated as soon as a new revision arrives <strong>(F)</strong></td><td>If you install a specific revision, it will be updated as soon as a new revision arrives <strong>(G)</strong></td></tr>
<tr><td>—</td><td>—</td><td>If you want to delay your specific revision being replaced by a new revision, you should use a “postpone any refreshes by N hours” feature</td></tr>
<tr><td>—</td><td>To resume tracking latest, uninstall+reinstall the snap <strong>(H)</strong></td><td>To prepone the postponed refresh, … ?</td></tr>
</table>

If that’s an accurate summary, then I don’t think we should tell you how to install a particular revision at all any more. Except for (E), the proposals may make sense for end users (safe reversions, avoid marooning), but they would make revisions practically useless for developers:

(B) The past three revisions alone won’t be enough for bisecting bugs, and sometimes won’t be enough even for choosing a build to promote. (“QA has finished manual testing of the 10am edge build, it’s good.” “Too late, we’ve published 16 builds to edge since then!”)

(C) build.snapcraft.io wouldn’t be able to say anything more specific than “This might work only if you’ve installed this revision in the past”, which would be almost comically vague.

(D) build.snapcraft.io couldn’t tell you whether the feature will _ever_ work for you, unless you’re currently signed in to U1 as a publisher/collaborator, and you probably aren’t signed in to U1 unless you’ve recently been registering/changing snap names.

If I’m wrong about most/all of that, and we do want to keep the instructions, then I think we should cover (A), (D), (F), and (H).

**Comment by evandandrea** [comment]
When the Forum thread talks about keeping revisions around, it means locally caching them. If I am the publisher of a snap I can still install by revision for any revision ever published. I've just confirmed this with the Store team.

**Comment by matthewpaulthomas** [comment]
Okay, I’m glad I misunderstood (B). Now, how about (C) or (E)? For example, could we address (C) by giving people instructions to install the snap in a container or something, so it’s not trying to revert from the currently-installed version (and not potentially corrupting your non-test data)?

Meanwhile, to fix the UI to match current reality, what is (A) and (D)? Once we have more of these sorted out, I’ll report a separate issue to get the instructions fixed.

**Comment by evandandrea** [comment]
A and D: Four times a day the snap will be automatically refreshed if any new revisions have been published.

C: Publishers (and I hope collaborators; @noise can confirm) can install any published revision regardless of whether they've previously installed it. Regardless of whether you install it in a container or natively, snapd will update from it if a new revision becomes available.

E: Very good point. Given that the Store will [not show the publisher in every case](https://github.com/canonical-ols/build.snapcraft.io/issues/646#issuecomment-296752094), I think we should change "The installed snap will not be auto-updated." to say:
```
You must `snap login` with the publisher account to install by specific revision.
Alternatively, you can install the most recent revision with `snap install $snap_name`.
```

I'd hate to drop it entirely; we'd be taking away the hint that they can bisect problems.

**Comment by matthewpaulthomas** [comment]
@evandandrea Thanks. However, what you’ve labelled as “A and D” (who can currently install a revision?) seems to be a restatement of F (_if_ you can install a revision, it will be automatically updated). I’ve now reported #694 for fixing the current text, so if you know the current behavior of A and D, please fill them in there.

**Comment by evandandrea** [comment]
Sorry about that. This is the current experience for attempting to install a snap by-revision for which you are not the publisher:
```
$ snap find storj
Name        Version  Developer  Notes  Summary
storjshare  2.5.1    popey      -      farm data on the Storj network.

$ sudo snap install storjshare --revision=1
error: cannot install "storjshare": snap not found

$ sudo snap install storjshare
storjshare 2.5.1 from 'popey' installed
```

**Comment by solazio** [comment]
Not relevant for snapcraft.io
