### ISSUE TITLE
When already logged into SSO, should check if I own the name before asking me to register it again

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#652]
<img width="1069" alt="screen shot 2017-04-21 at 10 32 54" src="https://cloud.githubusercontent.com/assets/1523179/25272088/72b48566-267e-11e7-83eb-643c1dbd81d9.png">

Steps to reproduce:

1. Remove an already set up repository with a registered name.
1. Re-add this repository.
1. Click the log in to SSO button.

What happens:

- You are asked to register a name you already own.

What should happen:

- If the name in the snapcraft.yaml on the repo matches a name you already own, the existing name should be used.
- You should not be asked to register a name you already own.

**Comment by bartaz** [comment]
Right now it happens because newly added snap in LP needs to be authorized to be published under given name (which happens when name is registered in BSI).

But, as suggested, in case of a repo with existing snapcraft.yaml after user signs in to SSO we can check if they own the name in snapcraft.yaml and if they do we can auto-authorize this snap for given name.

Two potential edge cases to this solution:
1. User adds a new repo (that was never added before) but they already have snapcraft.yaml and have a name registered in the store (for example they registered it already using CLI) - it will be automatically shown as registered - which is probably a good thing.
2. User adds a repo with a name in snapcraft.yaml that is already registered and used in another of their snaps - this name will be detected as already registered (so available) and will be automatically authorized for a new (second) snap. Which will result in two snaps from different repos being registered under the same name (owned by same user).

Case 2) seems to partially be an issue (not noticed before) that we already have. Given user may have 2 separate GH repos with 2 different codebases, but if they both have snapcraft.yaml with the same name in them they can both be added to BSI and registered under (same) name from snapcraft.yaml.

**Comment by evandandrea** [comment]
Case 2 is okay, given that they'll just funnel revisions into edge from the multiple repositories. Nothing will break.

In case 1, will the effect be that I add this repo with an already registered name and pre-existing snapcraft.yaml to my dashboard, click the "Sign in…" (SSO) button, and then builds will kick off with no further action from me? If so, +1.

**Comment by solazio** [comment]
We check if the name is already owned when registering it on snapcraft.io
