### ISSUE TITLE
"My repos" dashboard: Visually highlight changes in the table

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#663]
When a user visits the "my repos" dashboard, any changes since the last visit (whether they be changed table cells or new rows) should be visually highlighted. The look of this still needs to be designed.

Do we also highlight when a row has been deleted? This could be very useful for organisation members.

**Comment by kwm14** [comment]
Hi @nottrobin 

In MAAS we currently have these states for table row actions/changes.

- table--success
- table--warning
- table--error
- table--information

### Visual reference
![maas-table-states](https://cloud.githubusercontent.com/assets/17748020/25619515/10a0706a-2f43-11e7-87fe-9d4bff57b6d4.png)

These status changes take affect if you add a node, commission a node etc. Positive actions will be visible but once the page is refreshed they disappear, but warning, error and info will remain unless the user resolves them.

Is this something we think could work? @carlaberkers @matthewpaulthomas

**Comment by matthewpaulthomas** [comment]
@kwm14 If I understand you correctly, the kinds of changes you’re talking about are showing **things you’ve done** in the UI. The kinds of changes Robin is talking about are showing **things someone else has done** while you were signed out.

In build.snapcraft.io, some things fall into both categories. Changing the snapcraft.yaml is an example: you might have done it while signed in, you might have done it while signed out, someone else might have done while you were signed in, or someone else might have done while you were signed out.

“Once the page is refreshed they disappear” is a common but weird behavior in Web apps, but I think this combination of possibilities means it isn’t practical for us. You shouldn’t have to reload a page, that you just loaded, because that’s the only way of dismissing notifications of changes that *someone else* made hours or weeks earlier.

Maybe we need two things:
- A brief (~5-second) highlight of the cell or row that has changed (as in Waffle, for example)
- A table listing recent events involving your repos, who performed them and when.

**Comment by Greggless** [comment]
Referencing this issue in regards to the [Daily Build](https://github.com/canonicalltd/snappy-design-squad/issues/84) work. 

Has this lived in triaged since 3 Jul?

**Comment by carlaberkers** [comment]
@Greggless @bartaz since the 12th of June - it would be worth looking through other issues and seeing if there are others that could be lumped under the daily build work. Would it be possible to produce a list? 

Thanks - Carla

**Comment by Greggless** [comment]
On it @carlaberkers, reading through @matthewpaulthomas' [B.S.I spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#) and seeing where Daily builds may have changes

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
