### ISSUE TITLE
Ensure styling consistency across all tables

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#672]
Each of the tables, on "My repos", "Add repos" and the "Builds" page, should have a consistent visual style.

This had some previous design work which hasn't yet been implemented, but it we should also check that this design work achieves the desired consistency.

This should include the question of whether and where the whole row should be clickable, rather than just links within the row.

**Comment by matthewpaulthomas** [comment]
I don’t think this needs any design work. All tables should use the visual design that Jamie did for the “Repos to build and publish” table in #321:
- [mockups (slides 29-40)](https://docs.google.com/a/canonical.com/presentation/d/1tge2i4paDDVTPAXHLWJgMioNmkEOxr7giVvy7nPILRU/edit?usp=sharing)
- [visual specification](https://github.com/canonical-ols/build.snapcraft.io/files/919644/my-repos.zip)

Probably this should be fixed at the same time as #349.

**Comment by matthewpaulthomas** [comment]
Jamie’s visual design (linked above) had one arguable issue, which was the use of color to highlight alternate rows.

Coloring alternate table rows helps you scan across the cells in a row, especially when there’s a big gap between the contents of adjacent columns. However, the coloring can be confused with selection or other highlighting whenever the table has one, two, or three rows (so that one of the styles is used by only one row). And it’s quite likely that a build.snapcraft.io user will have only one, two, or three repos.

Karl’s newer mockup of “Add repos” does not have the alternating colors:
![](https://cloud.githubusercontent.com/assets/17748020/26203954/14f7fb94-3bd5-11e7-9de6-55b394ea74e1.png)

So, let’s follow that style for all our tables.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
