### ISSUE TITLE
Metric of repos with a snapcraft.yaml

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#706]
We have registered name, but we don't yet have a metric of repos with a snapcraft.yaml. Can we please add this to bsi_developer_uptake?

**Comment by cjwatson** [comment]
Any new metric has to have both a way to work out the current value as an initialiser, and a way to keep it up to date when things change.  The update procedure is fairly easy in this case (we can do it from the GitHub webhook, plus a bit of code to handle newly-added repositories), but initialising is harder since we have to loop over all the GitHub repositories we know about while being careful not to run into the rate limit.  We may therefore have to loop over them in smaller chunks until we have a complete record in the database.  (At the moment we only store this information in memcached, which is good enough for the web UI but not good enough for metrics.)  We then need to attribute that to the users who set up the repositories in question in BSI, and combined with the chunking requirement that means that we need to start tracking repositories individually for metrics purposes in a way that we don't currently do.

I think it may make sense to do this after #621.  Fixing that is probably going to require adding a `Repository` table and then separately keeping track of which user added which repository in a link table.  Having done that work, it will be much easier to do this.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
