### ISSUE TITLE
Trying to delete snap on staging fails

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#709]
Trying to delete the USD snap from my account on staging returns a 404. Refreshing the page shows it already removed.

<img width="1440" alt="screen shot 2017-05-03 at 12 04 53" src="https://cloud.githubusercontent.com/assets/1523179/25669843/d0f97acc-2ff8-11e7-82fe-62bb3a715c4f.png">

**Comment by evandandrea** [comment]
It looks like if you try to remove four snaps in a row, the fourth one removes but stays in the UI. If you click remove on it again you get the 404.

**Comment by popey** [comment]
I'm seeing similar. 
![screenshot from 2017-05-04 11-36-57](https://cloud.githubusercontent.com/assets/1841272/25700102/08090062-30be-11e7-8245-ae14fd42b011.png)

**Comment by evandandrea** [comment]
Just saw this again. Removing a few snaps worked, until I got to this one. Refreshing the page didn't help.

<img width="1440" alt="screen shot 2017-05-04 at 14 17 04" src="https://cloud.githubusercontent.com/assets/1523179/25718536/799eaa90-30d4-11e7-8b43-bcda6398fcd1.png">

**Comment by bartaz** [comment]
This seems to be related to polling we do for repos listing/status.

Every 15 seconds we poll LP for updated list of user repos and their statuses.
I think that if such poll request is sent right before some repo is removed the response may return the repo that was just removed so that it will show up on the list. Second attempt to remove such repo fails (because it doesn't exist on LP anymore).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
