### ISSUE TITLE
Switch panes when "register the name" is clicked

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#725]
<img width="1070" alt="screen shot 2017-05-05 at 09 07 44" src="https://cloud.githubusercontent.com/assets/1523179/25746779/f0327abc-3172-11e7-8b72-24979d252cbe.png">
<img width="1054" alt="screen shot 2017-05-05 at 09 07 52" src="https://cloud.githubusercontent.com/assets/1523179/25746787/f4926b08-3172-11e7-89a2-f9cd98a89ddd.png">

Steps to reproduce:
1. Register a name for the snap
1. Upload a snapcraft.yaml with a different name in the `name:` field
1. Click the "Register the name" link

What happens:
- You are switched to the name registration box
- The box is pre-filled with the existing registered name

What should happen:
- On clicking "Register the name", the UI switches to the name registration pane
- The box is pre-filled with the name from snapcraft.yaml

**Comment by bartaz** [comment]
(The spec says)[https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.wyo3cgnn0ubx]:
> “Register the name” should close this panel and open the panel for changing the registered name, with the field set to the snapcraft.yaml name by default.

So the only bug here is that the name prefilled in input is the one already registered, not the one from snapcraft.yaml.

I don't think it would be a good UI to have a text link do an action like name registering. If we really want to register name directly from name mismatch panel it should be redesigned to have a 'Register new name' button. But - this will only be possible after signing in to the store, so a whole new set of states would be needed for the case when user is not signed in.

Right now link directs to a panel for registering the name, and that's the only panel that needs to deal with signing in to the store.

**Comment by evandandrea** [comment]
Switching panes is fine by me.

**Comment by evandandrea** [comment]
Updated to just cover switching panes.

**Comment by bartaz** [comment]
@matthewpaulthomas @ev

I'm not sure if I understand what is requested here:

> What happens:
> - You are switched to the name registration box
> ...
> What should happen:
> On clicking "Register the name", the UI switches to the name registration pane

How does "You are switched to the name registration box" differs from "UI switches to the name registration pane"? It seems like "What happens" is more or less the same as "What should happen".

As far as I understand the issue here is that we suggest registering new name (from snapcraft.yaml),  but when user clicks "Register the name" they go to "change register name" panel, where the currently registered name is pre-filled into input field.

So the fix here would be to keep the functionality of switching the panes, but to fill the input with name from snapcraft.yaml rather then currently registered name?

So I'd suggest:

What happens:
- You are switched to the name registration box
- The box is pre-filled with the existing registered name

What should happen:
- You are switched to the name registration box
- The box is pre-filled with the name from snapcraft.yaml

**Comment by matthewpaulthomas** [comment]
@bartaz Yes, that’s what the spec says. (“‘Register the name’ should close this panel and open the panel for changing the registered name, with the field set to the snapcraft.yaml name by default.”)

**Comment by evandandrea** [comment]
Sounds good to me.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
