### ISSUE TITLE
Long GitHub account name overflows “Name” column in table of repos

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#793]
1\. Sign in with a long GitHub name.
2\. Add a repo.

What happens: The repo name overflows the “Name” column, overlapping the contents of the “Configured” column.

![](https://cloud.githubusercontent.com/assets/19535238/26218579/eba885ee-3be1-11e7-9d60-b8444a9a72ed.png)

What should happen: The repo name remains entirely within its own cell.

[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5): “The “Name” cell should contain the repo name, in {organization}/{name} format, wrapping to multiple lines if necessary.”

It may save time to fix this at the same time as #334, the equivalent for snap names.

[Originally reported by @nataliabidart as part of #792.]

**Comment by bartaz** [comment]
@matthewpaulthomas  Wrapping the name will make given row higher then others. It's already breaking the layout of the row (as visible in the image above), where the background of expanded cell doesn't cover whole cell.

This may be hard to fix if we will allow name cell to expand to any possible height (assuming owner and repo names can be very long).

It would be good to have a visual design of how we want the My repos table to look with such long wrapped name and dropdown expanded.

**Comment by matthewpaulthomas** [comment]
Okay, full disclosure: This issue would _already_ have been avoided by following the spec, where I’d said that the repo name should be ellipsized at the beginning, so that the cell is always one line high.

However, seeing this report made me think about that solution, and I realized it wasn’t so great. It would cause an ugly zig-zag, where the same characters in your GitHub ID were in different positions depending on the length of the rest of the repo name:
```
|biancafernandapareira/red|
|…ncafernandapareira/green|
|…ancafernandapareira/blue|
|…afernandapareira/scarlet|
|…cafernandapareira/yellow|
```
So now I think the name should wrap instead. It’s already wrapping, because the ellipsizing was never implemented; but it needs to wrap on any character (word-break: break-all), rather than wrapping just on spaces/punctuation as it does now.

@bartaz I’m aware that wrapping would continue to make the row taller, but I think this is not as bad as the zig-zag. The reason “the background of [the] expanded cell doesn't cover [the] whole cell” seems to be (I’m shocked to discover) that the repo table isn’t a real HTML &lt;table&gt;. In real tables, all of a row’s cells are automatically as tall as the tallest one.

**Comment by bartaz** [comment]
@matthewpaulthomas Yes. These are not HTML tables for the same reason I believe MAAS "Table interactive" pattern is not real HTML table. While HTML table has some benefits (of keeping widths and heights of cells automatically) it's extremely hard to add custom styles or interactive elements (such as our dropdown) to HTML table.

So, while it's not perfect, it would probably still be simpler to make this custom cells expand to whole width then using real HTML table.

When it comes to usage of ellipsis as in spec - yes, it's not implemented for any of the columns at the moment (and I believe we don't have any bug or a card reported for that).
Although it won't be simple either, because CSS only supports ellipsis in the end of the text, so having it in the beginning or in the middle (as per spec) will require some custom implementation (possibly using JavaScript to cut the names).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
