### ISSUE TITLE
Consider updating breadcrumbs to fully use Vanilla pattern

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#872]
## Summary

We currently have slightly different breadcrumbs to those from Vanilla. Because of the heading right under the breadcrumb we don't have the last (current) item in the breadcrumb:

<img width="978" alt="screen shot 2017-07-05 at 13 30 54" src="https://user-images.githubusercontent.com/83575/27862595-4645b228-6186-11e7-9b8a-be0e295b3691.png">

Vanilla pattern assumes existence of the last item in the breadcrumb, so if we wan't to be consistent with the pattern we should include it as well:

<img width="976" alt="screen shot 2017-07-05 at 13 28 34" src="https://user-images.githubusercontent.com/83575/27862619-60aee44a-6186-11e7-9e39-cc911d04b6cd.png">

But this makes heading a bit redundant. We may possibly remove it, but the page without the main title looks rather strange and empty:

<img width="978" alt="screen shot 2017-07-05 at 13 29 05" src="https://user-images.githubusercontent.com/83575/27862629-7abdb5fa-6186-11e7-98a9-516314270c00.png">

Some design feedback is required how we could both use Vanilla pattern consistently with other websites and not make BSI look bad.

**Comment by matthewpaulthomas** [comment]
There are three reasonable possibilities: title the current page in the breadcrumbs, in a heading below the breadcrumbs, or both. In yesterday’s Design Patterns meeting I said that the first two options are more elegant, because they’re simpler and less repetitive, but which is best depends on the situation. For example, some apps may be too short on space to have a separate heading; news articles may often have titles too long for breadcrumbs (and it may not be reasonable to make authors provide a breadcrumbly version); and some sites may have so many navigation elements that they do need the repetition.

The outcome was that I’ll write a proposed guideline on when to take each approach ([snappy-design-squad#57](https://github.com/CanonicalLtd/snappy-design-squad/issues/57)), to guide the decision on which options Vanilla should make easy.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
