### ISSUE TITLE
Delete requires me to sign in

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#958]
## Summary

This message:- "You can remove this repo only if you registered the name doctl." makes no sense, when I am not *registering* a new snap, but removing one. 

## Process

Setup a snap in build.snapcraft.io - go through the whole process, registering a name, setup the yaml, have it build successfully.

## Current and expected result

I would expect a confirmation "This will prevent fooapp from building here anymore, are you sure?" but don't expect to have to do additional auth dances when all I want to do is tell build to _stop_ doing something I _already_ authed to do previously.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/30601006-be80c88c-9d58-11e7-821a-a085d1153311.png)

**Comment by bartaz** [comment]
Sign in before deleting is currently required to verify ownership of the snap name.

For organisation repositories, all organisation members can see the repo in BSI, but only user who registered the name can remove it.
To enforce it we need to require sign in before removing the snap.

**Comment by evandandrea** [comment]
I think we should come up with a more descriptive message. How about, "Snap names are registered to Snap Store accounts. You must sign in to the Snap Store before removing this repo."

@matthewpaulthomas

**Comment by matthewpaulthomas** [comment]
It would make sense to verify my ownership of snap name _X_, if I was trying to change a repo from releasing nothing to releasing _X_, or if I was trying to change it from releasing _W_ to releasing _X_.

Unfortunately I did not record, in the spec, why ownership of the snap name is important for deletion. So I can’t suggest text to explain it.

(It’s common for Web apps to make you reauthenticate for something highly consequential, like deleting your account. But if that was what we were doing here, we’d make you reauthenticate when removing any repo where the snap had more than _n_ daily active devices; whether you owned the snap name would be immaterial.)

**Comment by bartaz** [comment]
@matthewpaulthomas 

As far as I remember the idea behind this was to prevent users in the organisation who didn't add given repository from removing it.
The point there was that if organisation user deleted the repo they would not be able to add it back if they didn't register the name in first place (because the name is owned by another user who added the repo).
To prevent users from deleting a snap they can't add back (can't register its name again to be precise) we made sure only user who registered the name can remove the snap.

But to know if user registered the name, user needs to be signed in to the store.

We are not doing 'reauthentication' here. If the user is already signed in to the store (for example registered name or removed another snap in current session in BSI) they will not have to sign in again before deleting a snap. Signing in to the store is required only once per user session before they do some action related to the store (registering a name or deleting a snap).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
